name: Getting started
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Log the pre-build disk space
        run: df
      - name: Step 2 - Checkout the main GitHub branch
        uses: actions/checkout@v2
      - name: Step 3 - Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Step 4 - Log build tool versions
        run: |
          git --version
          python --version
      - name: Step 5 - Log the post-build disk space
        run: df
